name: Gerar APK do TCC2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet e Dependências Numéricas
        run: |
          pip install flet numpy

      - name: Compilar o Aplicativo Móvel (APK)
        run: |
          flet build apk --product "Termodinamica_Movel" --build-version "1.0.0"

      - name: Disponibilizar arquivo APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Termodinamica_Movel_APK
          path: build/apk/app-release.apk
