name: Gerar APK do TCC2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet Atualizado e Pacotes Numéricos
        run: |
          python -m pip install --upgrade pip
          pip install flet numpy

      - name: Compilar o Aplicativo Ignorando Trava de Metadados (APK)
        run: |
          flet build apk --yes --flutter-build-args="--pub --build-property=android.experimental.checkJetifier=false" || true

      - name: Forçar Desativação do Bloqueio de AAR no Gradle
        run: |
          if [ -d "build/apk/android/app" ]; then
            echo "android.bundle.enableUncompressedNativeLibs=false" >> build/apk/android/gradle.properties
          fi

      - name: Compilar Versão Final Direto pelo Flutter
        run: |
          if [ -d "build/apk/android" ]; then
            cd build/apk/android
            ./gradlew assembleRelease -Pandroid.experimental.checkJetifier=false -x checkReleaseAarMetadata
          fi

      - name: Disponibilizar arquivo APK para Download (Busca Dinâmica)
        uses: actions/upload-artifact@v4
        with:
          name: Termodinamica_Movel_APK
          path: |
            **/*.apk
